# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 629dc1cb2136fefda8e215f6f404963085a23352a2677d86fd212983387b350bd8a4aac4ea3bffc28d02d6134c85148365954ec36ab0b2e28cb830f1cee5f7cf

test:
  secret_key_base: 13fbfed0c89d5eb08799dc1b31e63acd6252c2b7c375b256bd7ea7489f313ec765cda3470f450deaf71f1362df689a97452b7f93341b426049b5bf85fb468994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
